
notifications:
  email:
    recipients:
      - humberto.a.sanchez.ii@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

dist: bionic

language: python

cache: pip

python:
  - "3.9.12"

# command to install dependencies
install:
  - pip install -r requirements.txt


# command to run tests
script: ${TRAVIS_BUILD_DIR}/runtests.sh
